### ISSUE TITLE
Version Bump to 0.6.1

### ISSUE THREAD

**Issue by michaelvanstraten** [slowli/jwt-compact#131]
I am currently relying on some changes to this crate in my crate [`actix-jwt-auth-middleware`](https://github.com/michaelvanstraten/actix-jwt-auth-middleware) that have not been published. Could you maybe do a minor version bump to allow me to publish my crate to crates.io using the new changes?

In particular, I am looking to use the code added in this commit b36dc020c6febbb7601cd369ef9f883dc68307af.

**Comment by michaelvanstraten** [comment]
@slowli Should I make a PR?

**Comment by slowli** [comment]
Sorry for the delayed response. The version in the current `master` branch should be 0.7.0 rather than 0.6.1 since it contains breaking changes (bumped MSRV and updates of public dependencies). Would publishing 0.7.0 work for you? If so, I can do it shortly.

**Comment by michaelvanstraten** [comment]
No worries, the major version bump is no problem for me.

**Comment by slowli** [comment]
Version 0.7.0 of the crate is now published.
