### ISSUE TITLE
Consider relaxing signature of struct TimeOptions

### ISSUE THREAD

**Issue by tomasol** [slowli/jwt-compact#140]
Currently the signature contains: `struct TimeOptions<F = fn() -> DateTime<Utc>> ` . I would like to propose using `Fn` instead of `fn`  the same way as it is defined in the impl block containing the `new` function. This would allow using closures as well as function pointers (which are already supported).

**Comment by slowli** [comment]
Hi! Could you please explain the change you would like to see? The `F = fn() -> DateTime<Utc>` part of the `TimeOptions` definition is the default value for the type parameter `F`. You *can* create options with any `F: Fn() -> DateTime<Utc>` using [`TimeOptions::new()`](https://docs.rs/jwt-compact/latest/jwt_compact/struct.TimeOptions.html#method.new), and you can use any such `TimeOptions<F>` in `Claims` methods, such as [`validate_expiration()`](https://docs.rs/jwt-compact/latest/jwt_compact/struct.Claims.html#method.validate_expiration).

**Comment by tomasol** [comment]
Thanks for your explanation, I've misread the signature and missed the fact that `F` is specifying just the default generic type.
