### ISSUE TITLE
compact_token for Es256k

### ISSUE THREAD

**Issue by l1x** [slowli/jwt-compact#192]
## Feature request

Would it be possible to have compact_token() implemented for Es256 / Es256k?

### Why?

Not to have to implement this functionality by the enduser.

### Alternatives

Looking at the implementation of compact_token() for Hs256 and implement it based on that.

**Comment by slowli** [comment]
Hi! [`compact_token`](https://slowli.github.io/jwt-compact/jwt_compact/trait.AlgorithmExt.html#tymethod.compact_token) is a part of the `AlgorithmExt` trait and is thus not restricted to any particular JWS algorithms. It should work for `Es256` and `Es256k` out of the box, and it [is tested](https://github.com/slowli/jwt-compact/blob/90669696e416a0a9cf343507207e680c9097bd1f/tests/shared/mod.rs#L54-L61) for [`Es256`](https://github.com/slowli/jwt-compact/blob/90669696e416a0a9cf343507207e680c9097bd1f/tests/algorithms.rs#L458) and [`Es256k`](https://github.com/slowli/jwt-compact/blob/90669696e416a0a9cf343507207e680c9097bd1f/tests/algorithms.rs#L400). Do you have problems using the method in this way?

**Comment by l1x** [comment]
For some weird reason it was not working for Es256. Thanks!
