### ISSUE TITLE
ability to extract signature and signed bytes from Token/UntrustedToken

### ISSUE THREAD

**Issue by thedavidmeister** [slowli/jwt-compact#5]
currently can only get header and claims but not signature

i'd like to be able to use `ed25519_dalek` with the signature bytes and signature directly

**Comment by slowli** [comment]
Hi, @thedavidmeister! Terribly sorry for the delayed response; somehow, didn't notice the notification. 

I've sketched a solution in #9. Does it correspond to what you had in mind? Feel free to review the PR; would be much appreciated.
